load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "GetUserUseCaseTest",
    srcs = glob(["java/**/*.kt"]),
    test_class = "com.example.domain.usecase.GetUserUseCaseTest",
    deps = [
        "//domain/usecase",
        "//domain/model",
        "@maven//:junit_junit",
    ],
)
